### ISSUE TITLE
Silicon Chicken

### ISSUE THREAD

**Issue by Raggady** [Migmag789/Migmodpacks#4]
Silicon Chicken has no output. "This Item is disabled"

**Comment by Migmag789** [comment]
Hello. Thank you for reporting the problem ! I will fix it for the next update :) I'll close the issue when I'll fix the problem. If you want, the AE2 silicon is automatically disabled because there's the Galacticraft silicon, but the item ID stays, so the silicon chicken always drops the disabled item. Thank you, that will be fixed in 1.6.3 ;)

**Comment by Migmag789** [comment]
Fixed :)
